extensions:
  sigv4auth:
    region: "us-west-2"

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
  prometheusremotewrite:
    endpoint: "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-6f1f8c01-d166-43d9-9ee4-36646029331e/api/v1/remote_write"
    auth:
      authenticator: sigv4auth
  

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheusremotewrite

service:
  extensions: [sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite, logging]
